### PR TITLE
Bug fixes

### LINKED ISSUE #21: Float coordinates for scooters
Make the scooters coordinates when register to float instead of auto string.

### LINKED ISSUE #22: Implement name to the scooter
Implement name to the scooter so it's easier to understand what scooter the user / admin is talking about.

Need to fix:
- Data dummy
- Register dunction
- Edit function
- Insert in history object

### LINKED ISSUE #23: Implement charging zone
Implement charging zone to charge the scooters.

Needs to fix:
- Dummy data
- Register city
- edit tax rate
- stop scooter

### LINKED ISSUE #25: Reduct user balance when stop a ride
Reduct user balance when stop a ride.
Look if user have atleast 50kr in balance.

### PR DESCRIPTION
**Pull request by FalkenDev**
Fixed all the recently bug fixes and removed totalKm in uiser history
fixed #21 - Fixed float coordinates for scooters instead of strings when registered.
fixed #22 - Implemented name to the scooters and fixed edit, regiser and dummy data.
fixed #23 - Implemented charging zone and rate for cities and scooter.
fixed #25 - Implemented so the user balance is reducted when stoping the rent and added min of 50 SEK to rent a bike.

### CODE REVIEW

File: v1/models/scooters.js [hunk 1]
```diff
@@ -694,8 +726,11 @@ const scooters = {
                 totalPrice: totalPrice
             }
 
+            let newBalance = user.balance - parseInt(totalPrice);
```
Comment (Jolpango) [inline v1/models/scooters.js]: parseFloat?

**Review by Jolpango — APPROVED** [review]
